name: Performance Run Bulk Upload - Test

permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

on:
  workflow_dispatch:
    inputs:
      sandbox:
        description: "Which Sandbox to push to."
        required: true
        type: "string"
        default: "ndr"
      num_patients:
        description: "How many patients to create (default = 1)"
        required: true
        type: "string"
        default: "1"
      file_count:
        description: "How many files per patient"
        required: true
        type: "string"
        default: "1"
      file_size:
        description: "File size in MB"
        required: true
        type: "string"
        default: "1"
      use_v2_process:
        description: "Use V2 Bulk Upload Process"
        required: true
        type: "boolean"
        default: false

jobs:
  bulk_upload:
    uses: ./.github/workflows/performance-base-run-bulk-upload.yml
    with:
      environment: development
      sandbox: "${{ inputs.sandbox }}"
      num_patients: "${{ inputs.num_patients }}"
      file_count: "${{ inputs.file_count }}"
      file_size: "${{ inputs.file_size }}"
      use_v2_process: "${{ inputs.use_v2_process }}"
    secrets:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ASSUME_ROLE }}